---
apiVersion: batch/v1
kind: Job
metadata:
  name: grid-job
spec:
  ttlSecondsAfterFinished: 172800
  backoffLimit: 4
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: atlas-grid-centos7
          image: atlasadc/atlas-grid-centos7
          env:
            - name: computingSite
              value: "$computingSite"
            - name: pandaQueueName
              value: "$pandaQueueName"
            - name: proxySecretPath
              value: "$proxySecretPath"
            - name: proxyContent
              value: "$proxyContent"
            - name: workerID
              value: "$workerID"
            - name: logs_frontend_w
              value: "$logs_frontend_w"
            - name: logs_frontend_r
              value: "$logs_frontend_r"
            - name: resourceType
              value: "$resourceType"
            - name: HARVESTER_WORKER_ID
              value: "$HARVESTER_WORKER_ID"
            - name: HARVESTER_ID
              value: "$HARVESTER_ID"
            - name: PANDA_JSID
              value: "$PANDA_JSID"
            - name: TMPDIR
              value: "/home/localuser"
          command: ["/usr/bin/bash"]
          args: ["-c", "cd; wget https://raw.githubusercontent.com/HSF/harvester/master/pandaharvester/harvestercloud/k8s_startup_script.py; python k8s_startup_script.py"]
      volumes:
        - name: atlas
          persistentVolumeClaim:
            claimName: csi-cvmfs-atlas-pvc
            readOnly: true
        - name: atlas-condb
          persistentVolumeClaim:
            claimName: csi-cvmfs-atlas-condb-pvc
            readOnly: true
        - name: atlas-nightlies
          persistentVolumeClaim:
            claimName: csi-cvmfs-atlas-nightlies-pvc
            readOnly: true
        - name: sft
          persistentVolumeClaim:
            claimName: csi-cvmfs-sft-pvc
            readOnly: true
        - name: grid
          persistentVolumeClaim:
            claimName: csi-cvmfs-grid-pvc
            readOnly: true
        - name: proxy-secret
          secret:
              secretName: proxy-secret