#!/usr/bin/env bash

DATE=`date -u`
NAME=`git config --global user.name`
BRANCH=`git rev-parse --abbrev-ref HEAD`
FILE=pandaharvester/commit_timestamp.py
echo timestamp = \"$DATE on $BRANCH \(by $NAME\)\" > $FILE
git add $FILE
exit 0