#!/usr/bin/env bash

basedir="$(dirname $0)/pre-commit.d"

for hook in $(ls -1 $basedir); do
    bash $basedir/$hook
    RESULT=$?
    if [ $RESULT != 0 ]; then
        echo "$hook returned non-zero: $RESULT, abort commit"
        exit $RESULT
    fi
done

exit 0
