apiVersion: v1
kind: Pod

metadata:
  name: comm-test

spec:
  template:
      spec:
          volumes:
          - name: shared-dir
            emptyDir: {}

          containers:
          - name: pilot
            image: fbarreir/comm
            volumeMounts:
            - name: shared-dir
              mountPath: /root/shared/
            env:
            - name: SHARED_DIR
              value: "/root/shared/"
            command: ["python"]
            args: ["/root/tests/pilot.py"]

          - name: evaluation
            image: fbarreir/comm
            volumeMounts:
            - name: shared-dir
              mountPath: /root/shared/
            env:
            - name: SHARED_DIR
              value: "/root/shared/"
            command: ["python"]
            args: ["/root/tests/evaluation.py"]