#!/bin/bash

# import env vars from sysconfig
source ${VIRTUAL_ENV}/etc/sysconfig/panda_harvester

SITE_PACKAGES_PATH=`python -c "from distutils.sysconfig import get_python_lib; print(get_python_lib())"`
python ${SITE_PACKAGES_PATH}/pandaharvester/harvestertest/renice.py
