CRIC_RAM_TAG = 'maxrss'
CRIC_CORE_TAG = 'corecount'
UNIFIED_QUEUE_TAG = 'ucore'
CAPABILITY_TAG = 'capability'

# basic resource types
BASIC_RESOURCE_TYPE_SINGLE_CORE = "SCORE"
BASIC_RESOURCE_TYPE_MULTI_CORE = "MCORE"